/*
 * This file is generated by jOOQ.
 */
package com.nrapendra.jooq;


import com.nrapendra.jooq.tables.BookmarkTag;
import com.nrapendra.jooq.tables.Bookmarks;
import com.nrapendra.jooq.tables.Tags;
import com.nrapendra.jooq.tables.UserPreferences;
import com.nrapendra.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.bookmark_tag</code>.
     */
    public static final BookmarkTag BOOKMARK_TAG = BookmarkTag.BOOKMARK_TAG;

    /**
     * The table <code>public.bookmarks</code>.
     */
    public static final Bookmarks BOOKMARKS = Bookmarks.BOOKMARKS;

    /**
     * The table <code>public.tags</code>.
     */
    public static final Tags TAGS = Tags.TAGS;

    /**
     * The table <code>public.user_preferences</code>.
     */
    public static final UserPreferences USER_PREFERENCES = UserPreferences.USER_PREFERENCES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
